- name: mainRecipe
  hosts: all
  vars:
   group_name: devops
   default_pass: Falabella1
   editor:
    name: vim
    state: present
   users:
    - nicolas
    - luchito
    - phillippe
  tasks:
   - name: Update all packages
     shell: "apt-get update -y"
   - name: install vim
     apt:
      name: "{{ editor.name }}"
      state: "{{ editor.state }}"
   - name: Create Group
     group:
      name: "{{ group_name }}"
      state: present
   - name: Create users
     user:
      name: "{{ item }}"
      group: "{{ group_name }}"
      password: "{{ default_pass}}"
     loop: "{{ users | flatten(1) }}"
   - name: copy app file
     copy:
       src: enviable.txt
       dest: /home/enviable-enviado.txt
       
       